@startuml
hide empty members
hide circle
skinparam class {
BackgroundColor white
ArrowColor Black
BorderColor Black
}

class "Instant Eats"{
determines customer ID()
}

"Instant Eats" --> Customer
Customer --> "Order Choice"
"Order Choice" --> Amount
Amount--> Customer
Amount --> "Payment Option"
"Payment Option" --> Customer

class Amount{
determines amount tendered()
}

class Customer {
Choose restaurant()
place order()
choose payment()
}

class "Order Choice" {
Fast food, Fast Casual, Cafes
view ordered items()
show price of items()
}

class "Payment Option"{
Cash on delivery
Online Payment
checkout()
rate()
close()
}

@enduml