@startuml
'https://plantuml.com/sequence-diagram

skinparam actorStyle awesome
"Program" as Program
" Provide User Information" as (Use)
Program --> (Reports Order Transaction)
:User: --> (Use)
Program --> (Menu Selection)
User --> (Customize Order)
User --> (Order Cancellationn)

center header "INSTANT EATS"

@enduml
